### ISSUE TITLE
[REQUEST] new categories here.

### ISSUE THREAD

**Issue by monolidth** [ReceiptManager/receipt-manager-app#1]
Hi, 
at the moment I added only 2 different categories. If a category is missing please tell me here.

**Supported categories**

- health

- grocery

I will update the post. If an new category is added.

**Comment by tillmannschatz** [comment]
Hi,

I think instead of a static list with categories, these should be editable by the user within the app.
- gasoline
- travel / vacation
- gifts
- private / work
- household maintenance
- car repairs
- electricity bill / gas bill
- ...

Another suggestion would be to add the possibility of organizing receipts in projects.
I for example like to track my expenses for small projects e.g. homeautomation, bathroom renovation, cargo xyz, ...
Then one could query how much one spent for the project in total or also per year / month ...

**Comment by monolidth** [comment]
Hi @tillmannschatz,

> I think instead of a static list with categories, these should be editable by the user within the app.

Great suggestion. This is already planned. 

>  Another suggestion would be to add the possibility of organizing receipts in projects.

Agree, there is could be some work. There is maybe a to restructure of the database is required e.g. add a new column in the SQL database. 

> Then one could query how much one spent for the project in total or also per year / month 
Yes, this is already implemented but a bug. 

Thanks for the suggestion and inspiration.

Regards,
William
