### ISSUE TITLE
[REQUEST] Show Receipt Items in APP

### ISSUE THREAD

**Issue by Dielee** [ReceiptManager/receipt-manager-app#11]

**Comment by monolidth** [comment]
I will do my best but it will take maybe a week because I train the `receipt-parser-neuronal` and I could not develop at the same time.

**Comment by Dielee** [comment]
Just take your time! Merry Christmas!

**Comment by Dielee** [comment]
Do you need sample receipts to train ?

**Comment by monolidth** [comment]
Well, I collect receipts. I will try to merge them into the [receipt-dataset](github.com/ReceiptManager/receipt-dataset). 
Merry Christmas!

**Comment by monolidth** [comment]
Do you have any receipts you like to share @Dielee ?
It would be helpful if you also submit the key-value pairs as json file. You can see the example format in the receipt-dataset.

**Comment by monolidth** [comment]
I start working on it. See commit: d8c31c1dcc1201764c54968083ecae4780e4e1f5

**Comment by Dielee** [comment]
Any updates for this ? :)

**Comment by monolidth** [comment]
Well, I pushed my current app today. I already parse the given receipt items in the network client. 
Receipt items are now shown in the input form.

Thus, there are some bugs related to flutter. Flutter introduce nullpointer safty with causes bugs in the listviewer see: https://stackoverflow.com/questions/65886342/null-check-operator-used-on-a-null-value-staggeredgridview

And at the moment, I don't have so much time to develop, since I'm currently studying.

**Comment by monolidth** [comment]
See: 4de7194bc918f0653e7a1bb5404991413d726990

**Comment by monolidth** [comment]
If receipt items are returned via json, a new receipt item listview appear. You can edit, add and delete receipt items as expected. This listview features a custom slider, like at the HistoryWidget. I fixed this boring alert message bug.
